add 6sense account ads performance
2x-data-ops/dataops-client-services pull request #225
Opened 2024-10-23 07:37 UTC by hafizasyraf72

2024-10-23 08:49 UTC, izztsfn requested changes
Some minor formatting changes to make. Thanks!

2024-10-23 08:49 UTC, izztsfn commented on Clients/Blend360/Normalization Script/Ads/blend360_db_6sense_ad_performance.sql
> +    ads_li ads
Ensure ads_li ads is in the same line as FROM

2024-10-23 08:49 UTC, izztsfn commented on Clients/Blend360/Normalization Script/Ads/blend360_db_6sense_ad_performance.sql
> +  CASE WHEN _liextractdate = '6/4/2024' THEN PARSE_DATE('%m/%d/%Y', '5/31/2024')
Follow the same CASE statement formatting in data_6sense CTE. That one looks correct. Do the same for the rest of the CASE statements, WHEN and ELSE in this CTE

2024-10-23 08:49 UTC, izztsfn commented on Clients/Blend360/Normalization Script/Ads/blend360_db_6sense_ad_performance.sql
> +lagged_li_6sense
Ensure lagged_li_6sense is in the same line as FROM

2024-10-23 08:49 UTC, izztsfn commented on Clients/Blend360/Normalization Script/Ads/blend360_db_6sense_ad_performance.sql
> +  QUALIFY ROW_NUMBER() OVER (PARTITION BY _campaignid, _6senseid, _date ORDER BY CASE WHEN _extractdate LIKE '%/%' THEN PARSE_DATE('%m/%e/%Y', _extractdate) WHEN _extractdate LIKE '%-%' THEN PARSE_DA
Too long. Can do something like this instead:

```
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY _campaignid, _6senseid, _date
  ORDER BY
    CASE
      WHEN _extractdate LIKE '%/%' THEN PARSE_DATE('%m/%e/%Y', _extractdate)
      WHEN _extractdate LIKE '%-%' THEN PARSE_DATE('%F', _extractdate)
    END
) = 1
```

2024-10-23 08:49 UTC, izztsfn commented on Clients/Blend360/Normalization Script/Ads/blend360_db_6sense_ad_performance.sql
> +    ON ads._adid = airtable_fields._ad_id
reduce one indentation for ON

2024-10-24 06:15 UTC, hafizasyraf72 commented on Clients/Blend360/Normalization Script/Ads/blend360_db_6sense_ad_performance.sql
> +    ads_li ads
<img width="200" alt="image" src="https://github.com/user-attachments/assets/7c4545de-11c9-486b-8272-c551d41c0355">

amended

2024-10-24 06:15 UTC, hafizasyraf72 commented on Clients/Blend360/Normalization Script/Ads/blend360_db_6sense_ad_performance.sql
> +    ON ads._adid = airtable_fields._ad_id
<img width="200" alt="image" src="https://github.com/user-attachments/assets/89f5cd2a-57b9-4424-9c37-07b9fdb360c5">

amended

2024-10-24 06:37 UTC, izztsfn approved these changes
Looks good formatting wise! Good job.

2024-10-24 06:39 UTC, merged