Initial Build Ads Performance Script for Rackspace (LinkedIn)
2x-data-ops/dataops-client-services pull request #226
Opened 2024-10-24 06:17 UTC by meoflaxz

Client: Rackspace
Type: Ads Performance Script
Platform: LinkedIn (for now)

Ticket: https://rackspace.wise-portal.com/request-summary.php?id=18

Just an initial build with airtable. Nothing serious

2024-10-24 07:12 UTC, izztsfn requested changes

2024-10-24 07:12 UTC, izztsfn commented on Clients/Rackspace/rackspace_ads_performance.sql
> +    SELECT
Do the same for all of the remaining CTEs, this and the rest after it bcs they are all not inline. Just reduce one indentation for the content and it should be okay

2024-10-24 07:12 UTC, izztsfn commented on Clients/Rackspace/rackspace_ads_performance.sql
> +      CASE WHEN _ads_per_campaign > 0 THEN _daily_budget / _ads_per_campaign
Follow this syntax for CASE statement:
```
CASE xxx
  WHEN xxx THEN xxx
  ELSE xx
END AS _xxx
```

2024-10-24 07:12 UTC, izztsfn commented on Clients/Rackspace/rackspace_ads_performance.sql
> +        ON acc.id = account_id
reduce on indentation for ON acc.id = account_id

2024-11-07 01:52 UTC, meoflaxz commented
Halo @izztsfn,

Just made the required amendment.

Now fixed indentation and uses INSERT instead CREATE OR REPLACE

2024-11-08 06:58 UTC, hafizasyraf72 approved these changes

2024-11-11 01:49 UTC, izztsfn approved these changes
Overall formatting looks good. Some minor comments for next time but i'll still approve this one

2024-11-11 01:49 UTC, izztsfn commented on Clients/Rackspace/rackspace_ads_performance.sql
> +  FROM `rackspace_linkedin.creatives` c
Remember to use the full table ID here (with the `x-marketing` in front) for readability next time

2024-11-11 01:50 UTC, merged