Standardization for carenet_health ads script
2x-data-ops/dataops-client-services pull request #228
Opened 2024-10-24 07:05 UTC by raaayden

Update :
1. Remove subqueries and nested CTE
2. Update format
3. Changes the flow for more optimize and remove redundancy

Left is new script Right is old script to compare no of rows:

1. x-marketing.carenet_health.linkedin_ads_performance
![image](https://github.com/user-attachments/assets/6cabd388-a48e-4c53-afe6-8e7575eadf86)
2. x-marketing.carenet_health.all_ads_performance
![image](https://github.com/user-attachments/assets/da7a1519-b41c-4573-97bc-bc0274587b7d)

2024-10-24 09:36 UTC, izztsfn requested changes
Some formatting changes to make. Otherwise pretty decently formatted already :D

2024-10-24 09:36 UTC, izztsfn commented on Clients/Carenet/Normalization Script/Ads/carenet_health_ads_performance.sql
Formatting wise, all good for this one

2024-10-24 09:36 UTC, izztsfn commented on Clients/Carenet/Normalization Script/Ads/carenet_health_all_ads_perf.sql
> +  FROM (
Create a new CTE for this to remove subquery

2024-10-24 09:36 UTC, izztsfn commented on Clients/Carenet/Normalization Script/Ads/carenet_health_all_ads_perf.sql
> +FROM (
Create a new CTE to remove subquery here

2024-10-24 09:36 UTC, izztsfn commented on Clients/Carenet/Normalization Script/Ads/carenet_health_all_ads_perf.sql
> +  FROM (
Remove this subquery

2024-10-24 09:36 UTC, izztsfn commented on Clients/Carenet/Normalization Script/Ads/carenet_health_all_ads_perf.sql
> +  FROM (
Remove subquery

2024-10-24 09:36 UTC, izztsfn commented on Clients/Carenet/Normalization Script/Ads/carenet_health_all_ads_perf.sql
> +      THEN NULL
Ensure the CASE statement syntax is consistent for the script. Refer the following:
```
CASE xxx
  WHEN xxx THEN xxx
  ELSE xx
END AS _xxx
```

Update the remaining CASE statements to follow the same syntax

2024-10-24 09:37 UTC, izztsfn commented
Also @raaayden be sure to update your progress for these scripts in the scheduled script tracker: https://p423itcaltn.sg.larksuite.com/base/MJyebpBYDaX3IKsuY0Ulhwv3gZb?table=tblKzo8GrW53mUQF&view=vewDViB0he

2024-10-28 06:46 UTC, raaayden commented
hello @izztsfn , thanks for the review, i have already updated the script !

2024-10-29 02:23 UTC, izztsfn approved these changes
Looks good! Approved

2024-10-29 02:32 UTC, merged