2 x 42151 jaggaer email engagement
2x-data-ops/dataops-client-services pull request #234
Opened 2024-10-30 06:34 UTC by azwansyafiq-2X

Standardization for Jaggaer email engagement script. 
Remove subquery, adjust styling.

2024-10-30 06:55 UTC, nazzatul21 commented
noting to comment all good :)

2024-10-30 08:05 UTC, raaayden approved these changes
everything looks fine so far. Perhaps it will be better for the prospects to move into a separate script which is tam_database_log

2024-10-30 08:59 UTC, izztsfn requested changes
Overall formatting looks great! Just some subqueries to remove and also replace Create statement with Truncate and Insert instead.

Also i hope you have checked the rows of this script to match the existing tables. This is to ensure that the formatting does not affect the existing solution. So a quick check wouldve been sufficient. Can refer [this slide, number 6](https://2xmarketing-my.sharepoint.com/:p:/g/personal/izzat_sofian_2x_marketing/Ed-Y15u-YSZOtl_V4L6eZ6gBFByJHCck1C-5E5DvDiYdAg?e=odot3p&nav=eyJzSWQiOjMwMSwiY0lkIjoxMzk1MzcxNTR9) i made last time

2024-10-30 08:59 UTC, izztsfn commented on Clients/Jaggaer/Analytics Script/Normalization_Script/Email_Engagement/jaggaer_db_email_engagement_log.sql
> +  FROM (
Create a new CTE to remove subquery

2024-10-30 08:59 UTC, izztsfn commented on Clients/Jaggaer/Analytics Script/Normalization_Script/Email_Engagement/jaggaer_db_email_engagement_log.sql
> +    SELECT *
Create a new CTE here to remove subquery

2024-10-30 08:59 UTC, izztsfn commented on Clients/Jaggaer/Analytics Script/Normalization_Script/Email_Engagement/jaggaer_db_email_engagement_log.sql
> +CREATE OR REPLACE TABLE `x-marketing.jaggaer.db_lead_campaign_pardot` AS
Use DML statement instead

2024-11-04 03:40 UTC, izztsfn approved these changes
Noice!

2024-11-04 03:40 UTC, merged

2024-11-04 03:49 UTC, izztsfn commented
@azwansyafiq-2X dont forget to update the approved script into the scheduler ya tq!!