rename the file from blend360_abm_density_score to blend360_abm_densi…
2x-data-ops/dataops-client-services pull request #239
Opened 2024-11-04 06:19 UTC by hafizasyraf72

…ty_score_new

2024-11-05 02:41 UTC, izztsfn requested changes
Overall formatting looks good! Just some minor changes to make

2024-11-05 02:41 UTC, izztsfn commented on Clients/Blend360/Analytics Script/ABM Score/blend360_abm_density_score_new.sql
> +  END AS awareness_score_change,
I think you can replace this CASE statement with IF to make it much simpler and readable. Example:
![image](https://github.com/user-attachments/assets/752c8a8a-28a9-4012-9ce4-d2872d45e9a3)

Then you can update the rest of the following CASE statement as highlighted in the pic above

2024-11-06 03:46 UTC, hafizasyraf72 commented on Clients/Blend360/Analytics Script/ABM Score/blend360_abm_density_score_new.sql
> +  ROW_NUMBER() OVER(
done

2024-11-06 03:46 UTC, hafizasyraf72 commented on Clients/Blend360/Analytics Script/ABM Score/blend360_abm_density_score_new.sql
> +  ROW_NUMBER() OVER(
done

2024-11-06 05:03 UTC, izztsfn commented on Clients/Blend360/Analytics Script/ABM Score/blend360_abm_density_score_new.sql
> +  ROW_NUMBER() OVER(
I do not see any new commits. Have you pushed it? @hafizasyraf72

2024-11-06 06:13 UTC, hafizasyraf72 commented on Clients/Blend360/Analytics Script/ABM Score/blend360_abm_density_score_new.sql
> +  END AS awareness_score_change,
done as well. you can verify already ya @izztsfn

2024-11-06 06:17 UTC, izztsfn approved these changes
Looks good!

2024-11-06 06:17 UTC, merged