std emburse email engagement log
2x-data-ops/dataops-client-services pull request #246
Opened 2024-11-07 07:54 UTC by hafizasyraf72

2024-11-07 10:32 UTC, meoflaxz requested changes
Just trailing % wildcard issues, all good though!

2024-11-07 10:32 UTC, meoflaxz commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +  AND email NOT LIKE '%emburse.com%'
Not recommended to put a trailing % wildcard at the end if we know there's nothing after the search term

2024-11-08 06:55 UTC, hafizasyraf72 commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +  AND email NOT LIKE '%emburse.com%'
done amend and remove the wildcard at the end of email @meoflaxz

2024-11-08 07:24 UTC, meoflaxz approved these changes

2024-11-08 07:25 UTC, merged