Initial Build Analytics Script for Gibraltar
2x-data-ops/dataops-client-services pull request #263
Opened 2024-12-02 06:52 UTC by aiem2x

Client: Gibraltar
Type: Analytics Script

Ticket: https://gibraltarba.wise-portal.com/request-summary.php?id=471

Client wants to track seminar registrant. Just a normal contact list data.

2024-12-03 06:19 UTC, hafizasyraf72 requested changes
almost perfect, just indent the field that represent insert statement

2024-12-03 06:19 UTC, hafizasyraf72 commented on Clients/Gibraltar/Analytics_Script/gibraltar_ate_2025_contact_detail.sql
> +_hotel,
indent all of this insert field (line 8 until 28)

2024-12-04 02:22 UTC, aiem2x commented on Clients/Gibraltar/Analytics_Script/gibraltar_ate_2025_contact_detail.sql
> +_hotel,
Fixed indentation at latest commit

2024-12-10 02:22 UTC, hafizasyraf72 approved these changes

2024-12-10 02:22 UTC, merged